; =================================================================
; Prayer Times Settings
; =================================================================

[Variables]
CurrentVersion=5.4
; --- Location Settings ---
Language=English
RegionA=Middle East
Country=Saudi Arabia
Region=Makkah
City=Makkah
Latitude=21.389082222222
Longitude=39.857911666667
Timezone=3

; --- Calculation Method Settings ---

CalcMethod=Makkah
AsrMethod=Standard
SkinHeight=400


